#!/usr/bin/env julia
# ============================================================
# gmrfvs.jl
#
# Variance-Stable GMRF MLE using Hutch/SLQ + PCG.
#
# Uses a variance-stable precision matrix Q:
#   - Diagonal:     [1 + ρ²(d_i − 1)] / σ²_i
#   - Off-diagonal: −ρ/(σ_a·σ_z) per edge (unnormalized)
#
# When the input edgelist is a spanning tree/forest (generated by
# `src/create/sample.jl` with the "tree" sampler), this Q gives
# degree-independent marginal variances: Var(a_i) = σ²_a / (1 − ρ²).
#
# Usage:
#   julia --project=. src/estimate/gmrfvs.jl <path> [outcome] [flags]
#
# Flags:
#   --decompose      Run variance decomposition with 200 Hutchinson probes (default)
#   --decompose=N    Run variance decomposition with N probes
#   --no-decompose   Skip variance decomposition
#   --maxdeg=N       Remove firms/managers with degree > N before estimation
#
# Input:
#   temp/samples/<chunk>/<sample>/edgelist.parquet
#   (typically temp/samples/<chunk>/tree/edgelist.parquet)
#
# Output:
#   output/gmrfmle-vs/<chunk>/<sample>/estimates.txt
#   output/gmrfmle-vs_maxdeg<N>/<chunk>/<sample>/estimates.txt  (with --maxdeg)
# ============================================================

using Pkg
Pkg.activate(".")

using Parquet2
using DataFrames
using Optim
using FiniteDiff
using SparseArrays
using LinearAlgebra
using Statistics
using Random
using Printf: @printf, @sprintf

BLAS.set_num_threads(1)

to_float_nan(x) = x isa Missing ? NaN : Float64(x)

safe_id(s::AbstractString) = replace(s, ":" => "_")

# ============================================================
# 0) Pre-estimation filters
# ============================================================

function filter_maxdeg(df::DataFrame, maxdeg::Int; verbose::Bool=true)
    firm_deg   = combine(groupby(df, :frame_id_numeric), nrow => :deg)
    person_deg = combine(groupby(df, :person_id),        nrow => :deg)

    keep_firms   = Set(firm_deg[firm_deg.deg   .<= maxdeg, :frame_id_numeric])
    keep_persons = Set(person_deg[person_deg.deg .<= maxdeg, :person_id])

    n_before = nrow(df)
    df_out = filter(row -> row.frame_id_numeric in keep_firms &&
                           row.person_id in keep_persons, df)

    if verbose
        n_firms_dropped   = nrow(firm_deg)   - length(keep_firms)
        n_persons_dropped = nrow(person_deg) - length(keep_persons)
        @printf("maxdeg=%d: dropped %d firms, %d managers, %d→%d edges\n",
                maxdeg, n_firms_dropped, n_persons_dropped, n_before, nrow(df_out))
    end
    return df_out
end

# ============================================================
# 1) Sufficient statistics for V
# ============================================================

function build_V_stats(
    f_rows::Vector{Int},
    m_cols::Vector{Int},
    y::Vector{Float64},
    N_f::Int,
    N_m::Int
)
    K = length(y)
    @assert length(f_rows) == K
    @assert length(m_cols) == K

    proj_f = zeros(Float64, N_f)
    proj_m = zeros(Float64, N_m)
    cnt_f  = zeros(Float64, N_f)
    cnt_m  = zeros(Float64, N_m)

    @inbounds for k in 1:K
        f = f_rows[k]
        m = m_cols[k]
        val = y[k]
        cnt_f[f] += 1.0
        cnt_m[m] += 1.0
        proj_f[f] += val
        proj_m[m] += val
    end

    projected_y = vcat(proj_f, proj_m)

    A_obs = sparse(f_rows, m_cols, ones(Float64, K), N_f, N_m)

    VtV = [spdiagm(0 => cnt_f)  A_obs;
           A_obs'              spdiagm(0 => cnt_m)]

    return projected_y, VtV
end

# ============================================================
# 2) PCG with workspace
# ============================================================

mutable struct PCGWorkspace
    x::Vector{Float64}
    r::Vector{Float64}
    z::Vector{Float64}
    p::Vector{Float64}
    Ap::Vector{Float64}
end
PCGWorkspace(n::Int) = PCGWorkspace(zeros(n), zeros(n), zeros(n), zeros(n), zeros(n))

function pcg_solve!(
    ws::PCGWorkspace,
    mulA!,
    b::AbstractVector{<:Real};
    tol::Real=1e-6,
    maxiter::Int=700,
    Mdiag::Union{Nothing,AbstractVector{<:Real}}=nothing,
    diag_floor::Real=1e-12
)
    x, r, z, p, Ap = ws.x, ws.r, ws.z, ws.p, ws.Ap
    n = length(b)

    fill!(x, 0.0)
    @inbounds for i in 1:n
        r[i] = Float64(b[i])
    end

    nb = norm(r)
    if nb == 0.0
        return x, true, 0, 0.0
    end

    if Mdiag === nothing
        z .= r
    else
        @inbounds for i in 1:n
            d = Float64(Mdiag[i])
            d = (d > diag_floor) ? d : diag_floor
            z[i] = r[i] / d
        end
    end

    p .= z
    rz = dot(r, z)
    if !isfinite(rz)
        return x, false, 0, Inf
    end

    for it in 1:maxiter
        mulA!(Ap, p)
        denom = dot(p, Ap)
        if !(isfinite(denom) && denom > 0)
            return x, false, it, Inf
        end

        α = rz / denom
        if !isfinite(α)
            return x, false, it, Inf
        end

        @inbounds @simd for i in 1:n
            x[i] += α * p[i]
            r[i] -= α * Ap[i]
        end

        relres = norm(r) / nb
        if relres <= tol
            return x, true, it, relres
        end

        if Mdiag === nothing
            z .= r
        else
            @inbounds for i in 1:n
                d = Float64(Mdiag[i])
                d = (d > diag_floor) ? d : diag_floor
                z[i] = r[i] / d
            end
        end

        rz_new = dot(r, z)
        if !(isfinite(rz_new) && rz != 0.0)
            return x, false, it, Inf
        end

        β = rz_new / rz
        if !isfinite(β)
            return x, false, it, Inf
        end

        @inbounds @simd for i in 1:n
            p[i] = z[i] + β * p[i]
        end
        rz = rz_new
    end

    return x, false, maxiter, norm(r) / nb
end

# ============================================================
# 3) SLQ logdet with workspace
# ============================================================

mutable struct SLQWorkspace
    z::Vector{Float64}
    q::Vector{Float64}
    q0::Vector{Float64}
    w::Vector{Float64}
    α::Vector{Float64}
    β::Vector{Float64}
end
SLQWorkspace(n::Int, k::Int) = SLQWorkspace(
    Vector{Float64}(undef, n),
    zeros(n),
    zeros(n),
    zeros(n),
    zeros(k),
    zeros(max(k-1, 0))
)

function slq_logdet_spd_mul_cached!(
    mulA!,
    n::Int,
    ws::SLQWorkspace;
    m::Int=30,
    k::Int=30,
    seed::Int=1,
    jitter::Real=1e-12,
    ritz_floor::Real=1e-14
)
    k_eff = min(k, n)
    rng = MersenneTwister(seed)

    z, q, q0, w = ws.z, ws.q, ws.q0, ws.w
    αfull, βfull = ws.α, ws.β

    total = 0.0
    nz = sqrt(n)

    for _ in 1:m
        @inbounds for i in 1:n
            z[i] = rand(rng, Bool) ? 1.0 : -1.0
        end

        @. q = z / nz
        fill!(q0, 0.0)
        beta_prev = 0.0

        fill!(αfull, 0.0)
        fill!(βfull, 0.0)
        t_stop = k_eff

        for t in 1:k_eff
            mulA!(w, q)
            if jitter != 0
                @. w = w + jitter*q
            end

            αfull[t] = dot(q, w)
            @. w = w - αfull[t]*q - beta_prev*q0

            if t < k_eff
                beta_prev = norm(w)
                if !isfinite(beta_prev)
                    return NaN
                end
                βfull[t] = beta_prev

                if beta_prev < 1e-14
                    t_stop = t
                    break
                end

                q0 .= q
                @. q = w / beta_prev
            end
        end

        αv = copy(view(αfull, 1:t_stop))
        βv = (t_stop > 1) ? copy(view(βfull, 1:(t_stop-1))) : Float64[]

        T = SymTridiagonal(αv, βv)

        local E
        try
            E = eigen(T)
        catch
            return NaN
        end

        vals = E.values
        u1   = @view E.vectors[1, :]

        s = 0.0
        @inbounds for j in 1:length(vals)
            λj = vals[j] > ritz_floor ? vals[j] : ritz_floor
            s += log(λj) * (u1[j]^2)
        end

        total += (nz^2) * s
    end

    return total / m
end

# ============================================================
# 4) Prepare data
# ============================================================

# Union-Find check: returns true iff the bipartite graph encoded by A_fm is a
# forest (acyclic).  Uses path-halving for O(K·α(N)) time.
function _is_forest(A_fm::SparseMatrixCSC)
    N_F, N_M = size(A_fm)
    N = N_F + N_M
    parent = collect(1:N)

    function find!(u::Int)
        while parent[u] != u
            parent[u] = parent[parent[u]]   # path halving
            u = parent[u]
        end
        return u
    end

    rows = rowvals(A_fm)
    for j in 1:N_M
        pv = find!(N_F + j)
        for idx in nzrange(A_fm, j)
            pu = find!(rows[idx])
            pu == pv && return false          # cycle detected
            parent[pv] = pu                   # merge (pv under pu)
            pv = find!(N_F + j)               # refresh after merge
        end
    end
    return true
end

function prepare_data(
    df::DataFrame;
    outcome::Symbol,
    verbose::Bool=true
)
    required = [:frame_id_numeric, :person_id, outcome]
    for c in required
        hasproperty(df, c) || error("Missing required column: $(c)")
    end

    if nrow(df) == 0
        error("Empty dataset.")
    end

    if verbose
        @printf("Raw rows: %d\n", nrow(df))
        nunique = length(unique(zip(df.frame_id_numeric, df.person_id)))
        if nunique != nrow(df)
            @printf("WARNING: duplicate (firm,person) pairs: rows=%d, unique_edges=%d\n",
                    nrow(df), nunique)
        else
            @printf("Unique edges: %d\n", nunique)
        end
    end

    y_raw_all = map(to_float_nan, df[!, outcome])
    keep = map(isfinite, y_raw_all)
    d = df[keep, :]
    y_raw = Float64.(y_raw_all[keep])

    if verbose
        @printf("After non-missing %s filter: K=%d\n", String(outcome), length(y_raw))
    end

    if length(y_raw) == 0
        error("No usable observations after filtering non-missing $(outcome).")
    end

    firms  = unique(d.frame_id_numeric)
    people = unique(d.person_id)

    N_F = length(firms)
    N_M = length(people)
    K   = nrow(d)

    if verbose
        @printf("Indexing IDs... N_F=%d, N_M=%d, K=%d\n", N_F, N_M, K)
    end

    firm_to_idx   = Dict{eltype(firms),Int}(f => i for (i,f) in enumerate(firms))
    person_to_idx = Dict{eltype(people),Int}(p => i for (i,p) in enumerate(people))

    f_rows = Vector{Int}(undef, K)
    m_cols = Vector{Int}(undef, K)
    @inbounds for k in 1:K
        f_rows[k] = firm_to_idx[d.frame_id_numeric[k]]
        m_cols[k] = person_to_idx[d.person_id[k]]
    end

    μy = mean(y_raw)
    y_raw .-= μy

    y_std = std(y_raw)
    if !(isfinite(y_std) && y_std > 0)
        error("Outcome has zero/invalid std. Cannot scale.")
    end
    y = y_raw ./ y_std
    ydot = dot(y, y)

    if verbose
        @printf("Outcome scaling: mean removed, y_std=%.6g\n", y_std)
        @printf("Building V stats and sparse structures...\n")
    end

    projected_y, VtV = build_V_stats(f_rows, m_cols, y, N_F, N_M)

    A_fm = sparse(f_rows, m_cols, ones(Float64, K), N_F, N_M)
    A_fm.nzval .= 1.0
    At_fm = copy(transpose(A_fm))

    if !_is_forest(A_fm)
        @warn "Input graph contains a cycle; variance-stable Q no longer guarantees " *
              "degree-independent marginal variances. Proceeding anyway."
    end

    d_f = vec(sum(A_fm; dims=2))
    d_m = vec(sum(A_fm; dims=1))
    if any(d_f .<= 0) || any(d_m .<= 0)
        error("Zero-degree node detected; investigate IDs / data construction.")
    end

    if verbose
        @printf("Max degree: firm=%d, manager=%d\n", Int(maximum(d_f)), Int(maximum(d_m)))
    end

    return (y=y, ydot=ydot, y_std=y_std,
            A_fm=A_fm, At_fm=At_fm, d_f=d_f, d_m=d_m,
            projected_y=projected_y, VtV=VtV,
            K=K, N_F=N_F, N_M=N_M)
end

# ============================================================
# 5) Variance-stable Q operator
# ============================================================

mutable struct QOpVS{TA,TAT}
    A::TA
    At::TAT
    d_f::Vector{Float64}
    d_m::Vector{Float64}
    Nf::Int
    inv_sa2::Float64
    inv_sz2::Float64
    cross::Float64
    rho_sq::Float64
    tmpF::Vector{Float64}
    tmpM::Vector{Float64}
end

function (op::QOpVS)(y::Vector{Float64}, x::Vector{Float64})
    n  = length(x)
    Nf = op.Nf
    @views xf = x[1:Nf]
    @views xm = x[(Nf+1):n]
    @views yf = y[1:Nf]
    @views ym = y[(Nf+1):n]

    inv_sa2 = op.inv_sa2
    inv_sz2 = op.inv_sz2
    cross   = op.cross
    rho_sq  = op.rho_sq

    # Diagonal: [1 + ρ²(d_i − 1)] / σ²_i
    @inbounds for i in 1:Nf
        yf[i] = (1.0 + rho_sq * (op.d_f[i] - 1.0)) * inv_sa2 * xf[i]
    end
    Nm = n - Nf
    @inbounds for j in 1:Nm
        ym[j] = (1.0 + rho_sq * (op.d_m[j] - 1.0)) * inv_sz2 * xm[j]
    end

    # Off-diagonal: −cross * A (unnormalized)
    mul!(op.tmpF, op.A, xm)
    @. yf -= cross * op.tmpF

    mul!(op.tmpM, op.At, xf)
    @. ym -= cross * op.tmpM

    return y
end

mutable struct MOp{TQ,TV}
    qop::TQ
    VtV::TV
    tmpMV::Vector{Float64}
    λ::Float64
end

function (op::MOp)(y::Vector{Float64}, x::Vector{Float64})
    op.qop(y, x)
    mul!(op.tmpMV, op.VtV, x)
    @. y = y + op.λ * op.tmpMV
    return y
end

# ============================================================
# 6) Cached objective
# ============================================================

mutable struct NLLCache{TQ,TM}
    dV::Vector{Float64}
    Mdiag::Vector{Float64}
    pcg::PCGWorkspace
    slqQ::SLQWorkspace
    slqM::SLQWorkspace
    qop::TQ
    mop::TM
end

function nll_hutch_cached_vs(
    params,
    ydot::Float64,
    projected_y::Vector{Float64},
    K::Int,
    d_f::Vector{Float64},
    d_m::Vector{Float64},
    cache::NLLCache;
    m::Int=30,
    k::Int=30,
    seed::Int=20260126,
    jitter::Real=1e-12,
    ritz_floor::Real=1e-14,
    cg_tol::Real=1e-6,
    cg_maxiter::Int=700,
    cg_diag_floor::Real=1e-12
)
    BIG = 1e30

    ρ  = 0.99 * tanh(params[1])
    σa = exp(params[2])
    σz = exp(params[3])
    σe = exp(params[4])

    if !(isfinite(ρ) && isfinite(σa) && isfinite(σz) && isfinite(σe)) || (σe <= 0) || (σa <= 0) || (σz <= 0)
        return BIG
    end

    λ = 1.0 / (σe^2)
    inv_sa2 = 1.0 / (σa^2)
    inv_sz2 = 1.0 / (σz^2)
    cross   = ρ / (σa * σz)
    rho_sq  = ρ^2

    n  = length(projected_y)
    Nf = cache.qop.Nf

    cache.qop.inv_sa2 = inv_sa2
    cache.qop.inv_sz2 = inv_sz2
    cache.qop.cross   = cross
    cache.qop.rho_sq  = rho_sq
    cache.mop.λ       = λ

    dV = cache.dV
    Mdiag = cache.Mdiag
    @inbounds for i in 1:n
        if i <= Nf
            dq = (1.0 + rho_sq * (d_f[i] - 1.0)) * inv_sa2
        else
            j = i - Nf
            dq = (1.0 + rho_sq * (d_m[j] - 1.0)) * inv_sz2
        end
        Mdiag[i] = dq + λ * dV[i]
    end

    xsol, ok, _, _ = pcg_solve!(cache.pcg, cache.mop, projected_y;
        tol=cg_tol, maxiter=cg_maxiter, Mdiag=Mdiag, diag_floor=cg_diag_floor
    )
    if !ok
        return BIG
    end

    quad_term = dot(projected_y, xsol)
    if !isfinite(quad_term)
        return BIG
    end

    ldQ = slq_logdet_spd_mul_cached!(cache.qop, n, cache.slqQ;
        m=m, k=k, seed=seed + 0, jitter=jitter, ritz_floor=ritz_floor
    )
    ldM = slq_logdet_spd_mul_cached!(cache.mop, n, cache.slqM;
        m=m, k=k, seed=seed + 10_000, jitter=jitter, ritz_floor=ritz_floor
    )
    if !(isfinite(ldQ) && isfinite(ldM))
        return BIG
    end

    val = 0.5 * ( (K * (2.0*log(σe))) + (ldM - ldQ) + (λ * ydot) - ((λ^2) * quad_term) )
    return isfinite(val) ? val : BIG
end

# ============================================================
# 6.5) Hutchinson variance decomposition
# ============================================================

function hutch_variance_decomp_vs(
    prep,
    p̂::Vector{Float64};
    m::Int=50,
    seed::Int=20260126,
    cg_tol::Float64=1e-6,
    cg_maxiter::Int=700,
    verbose::Bool=true
)
    ρ  = 0.99 * tanh(p̂[1])
    σa = exp(p̂[2])
    σz = exp(p̂[3])
    σe = exp(p̂[4])

    inv_sa2 = 1.0 / σa^2
    inv_sz2 = 1.0 / σz^2
    cross   = ρ / (σa * σz)
    rho_sq  = ρ^2

    n = prep.N_F + prep.N_M

    qop = QOpVS(prep.A_fm, prep.At_fm, prep.d_f, prep.d_m, prep.N_F,
                inv_sa2, inv_sz2, cross, rho_sq,
                zeros(prep.N_F), zeros(prep.N_M))

    pcg_ws = PCGWorkspace(n)
    rng    = MersenneTwister(seed + 77_777)

    Qdiag = Vector{Float64}(undef, n)
    @inbounds for i in 1:prep.N_F
        Qdiag[i] = (1.0 + rho_sq * (prep.d_f[i] - 1.0)) * inv_sa2
    end
    @inbounds for j in 1:prep.N_M
        Qdiag[prep.N_F + j] = (1.0 + rho_sq * (prep.d_m[j] - 1.0)) * inv_sz2
    end

    acc_F     = 0.0
    acc_M     = 0.0
    acc_cross = 0.0
    n_ok      = 0

    v    = Vector{Float64}(undef, n)
    wv_f = Vector{Float64}(undef, prep.N_F)
    wv_m = Vector{Float64}(undef, prep.N_M)

    verbose && @printf("\n--- Variance decomposition (Hutchinson, m=%d) ---\n", m)

    t_decomp = @elapsed for t in 1:m
        @inbounds for i in 1:n
            v[i] = rand(rng, Bool) ? 1.0 : -1.0
        end

        u, ok, _, relres = pcg_solve!(pcg_ws, qop, v; tol=cg_tol, maxiter=cg_maxiter, Mdiag=Qdiag)
        if !ok
            verbose && @printf("[decomp] probe %d: PCG did not converge (relres=%.2e), skipping\n", t, relres)
            continue
        end
        n_ok += 1

        vf = view(v, 1:prep.N_F)
        vm = view(v, prep.N_F+1:n)
        uf = view(u, 1:prep.N_F)
        um = view(u, prep.N_F+1:n)

        @inbounds for i in 1:prep.N_F
            acc_F += prep.d_f[i] * vf[i] * uf[i]
        end

        @inbounds for j in 1:prep.N_M
            acc_M += prep.d_m[j] * vm[j] * um[j]
        end

        mul!(wv_f, prep.A_fm,  um)
        mul!(wv_m, prep.At_fm, uf)
        acc_cross += dot(vf, wv_f) + dot(vm, wv_m)
    end

    if n_ok == 0
        @warn "All decomposition probes failed (PCG non-convergence); variance decomposition unreliable."
        return (V_firm=NaN, V_manager=NaN, V_cross=NaN,
                V_eps=(σe * prep.y_std)^2, V_total=NaN,
                probes=m, pcg_converged=0)
    end

    scale     = prep.y_std^2 / (Float64(n_ok) * Float64(prep.K))
    V_firm    = acc_F     * scale
    V_manager = acc_M     * scale
    V_cross   = acc_cross * scale
    V_eps     = (σe * prep.y_std)^2
    V_total   = V_firm + V_manager + V_cross + V_eps

    if verbose
        @printf("Decomp time: %.1fs | PCG converged: %d/%d\n", t_decomp, n_ok, m)
        @printf("  V_firm    = %+.6f\n", V_firm)
        @printf("  V_manager = %+.6f\n", V_manager)
        @printf("  V_cross   = %+.6f\n", V_cross)
        @printf("  V_eps     = %+.6f\n", V_eps)
        @printf("  V_total   = %+.6f\n", V_total)
    end

    return (V_firm=V_firm, V_manager=V_manager, V_cross=V_cross,
            V_eps=V_eps, V_total=V_total,
            probes=m, pcg_converged=n_ok)
end

# ============================================================
# 7) Estimation
# ============================================================

function estimate_vs(
    df::DataFrame;
    outcome::Symbol=:lnR,
    HUTCH_M::Int=8,
    HUTCH_K::Int=15,
    CG_TOL::Float64=1e-6,
    CG_MAXITER::Int=700,
    iters::Int=1000,
    seed::Int=20260126,
    verbose::Bool=true,
    decomp_probes::Int=0
)
    @printf("\n--- Preparing data ---\n")
    prep = prepare_data(df; outcome=outcome, verbose=verbose)

    n = prep.N_F + prep.N_M
    @printf("\n--- Model dimensions ---\n")
    @printf("N_F=%d, N_M=%d, K=%d, n=%d\n", prep.N_F, prep.N_M, prep.K, n)
    @printf("HUTCH: m=%d, k=%d | PCG tol=%.2e, maxiter=%d | seed=%d\n",
            HUTCH_M, HUTCH_K, CG_TOL, CG_MAXITER, seed)

    dV = Vector{Float64}(diag(prep.VtV))

    qop = QOpVS(prep.A_fm, prep.At_fm, prep.d_f, prep.d_m,
                prep.N_F, 1.0, 1.0, 0.0, 0.0,
                zeros(prep.N_F), zeros(prep.N_M))

    mop = MOp(qop, prep.VtV, zeros(n), 1.0)

    cache = NLLCache(
        dV,
        zeros(n),
        PCGWorkspace(n),
        SLQWorkspace(n, HUTCH_K),
        SLQWorkspace(n, HUTCH_K),
        qop,
        mop
    )

    eval_counter = Ref(0)

    function obj(p)
        eval_counter[] += 1
        if verbose && (eval_counter[] == 1 || eval_counter[] % 10 == 0)
            @printf("[obj] eval=%d | p=(%.3g, %.3g, %.3g, %.3g)\n",
                    eval_counter[], p[1], p[2], p[3], p[4])
        end
        return nll_hutch_cached_vs(
            p, prep.ydot, prep.projected_y, prep.K,
            prep.d_f, prep.d_m, cache;
            m=HUTCH_M, k=HUTCH_K, seed=seed, jitter=1e-12,
            cg_tol=CG_TOL, cg_maxiter=CG_MAXITER
        )
    end

    @printf("\n--- Optimization (Nelder-Mead, variance-stable Q) ---\n")
    nm_opts = Optim.Options(iterations=iters, g_tol=1e-3, show_trace=verbose, show_every=50)
    delta   = 1e-4

    p0 = [atanh(0.5/0.99), log(0.7), log(0.04), log(0.4)]
    @printf("Initial p0 = (%.6g, %.6g, %.6g, %.6g)\n", p0[1], p0[2], p0[3], p0[4])

    res = nothing
    t_opt = @elapsed (res = optimize(obj, p0, NelderMead(), nm_opts))
    p̂ = Optim.minimizer(res)

    ρ̂  = 0.99 * tanh(p̂[1])
    σâ = exp(p̂[2]) * prep.y_std
    σẑ = exp(p̂[3]) * prep.y_std
    σê = exp(p̂[4]) * prep.y_std
    nll_hat = obj(p̂)

    converged = true
    for i in 1:4
        p_plus  = copy(p̂); p_plus[i]  += delta
        p_minus = copy(p̂); p_minus[i] -= delta
        if obj(p_plus) < nll_hat - 1e-2 || obj(p_minus) < nll_hat - 1e-2
            converged = false; break
        end
    end

    @printf("\n--- Done ---\n")
    @printf("Nelder-Mead: %d iters, %.1fs\n", Optim.iterations(res), t_opt)
    @printf("Converged: %s | obj evals: %d\n",
            string(converged), eval_counter[])
    @printf("NLL (scaled): %.6f\n", nll_hat)
    @printf("Estimates: rho=%.6f, sigma_a=%.6f, sigma_z=%.6f, sigma_eps=%.6f\n",
            ρ̂, σâ, σẑ, σê)

    decomp = nothing
    if decomp_probes > 0
        decomp = hutch_variance_decomp_vs(prep, p̂;
            m=decomp_probes, seed=seed, cg_tol=CG_TOL, cg_maxiter=CG_MAXITER,
            verbose=verbose)
    end

    return (ok=true,
            outcome=outcome, seed=seed,
            N_F=prep.N_F, N_M=prep.N_M, K=prep.K, n=n,
            y_std=prep.y_std,
            converged=converged,
            iterations=Optim.iterations(res),
            obj_evals=eval_counter[], opt_time=t_opt,
            nll=nll_hat, rho=ρ̂, sigma_a=σâ, sigma_z=σẑ, sigma_eps=σê,
            decomp=decomp)
end

# ============================================================
# 8) Path utilities
# ============================================================

function parse_sample_path(in_path::String)::Tuple{String,String,String}
    normalized = replace(in_path, "\\" => "/")
    parts = split(normalized, '/')

    temp_idx = findfirst(==("temp"), parts)
    samples_idx = findfirst(==("samples"), parts)

    if temp_idx === nothing || samples_idx === nothing || samples_idx != temp_idx + 1
        error("Path must contain 'temp/samples' directory structure: $in_path")
    end

    if length(parts) < samples_idx + 2
        error("Path must have format temp/samples/<chunk>/<sample>/file.parquet: $in_path")
    end

    chunk = parts[samples_idx + 1]
    sample_parts = parts[samples_idx + 2 : end - 1]
    sample = join(sample_parts, "/")

    out_dir = joinpath("output", "gmrfmle-vs", chunk, sample_parts...)
    out_path = joinpath(out_dir, "estimates.txt")

    return (chunk, sample, out_path)
end

# ============================================================
# 9) Main
# ============================================================

function main()
    positional = filter(a -> !startswith(a, "--"), ARGS)
    flags      = filter(a ->  startswith(a, "--"), ARGS)

    if length(positional) < 1
        println(stderr,
            "Usage:\n" *
            "  julia --project=. src/estimate/gmrfvs.jl <path/to/edgelist.parquet> [outcome] [flags]\n" *
            "\n" *
            "Flags:\n" *
            "  --decompose      Run variance decomposition with 200 Hutchinson probes (default)\n" *
            "  --decompose=N    Run variance decomposition with N probes\n" *
            "  --no-decompose   Skip variance decomposition\n" *
            "  --maxdeg=N       Remove firms/managers with degree > N before estimation\n" *
            "\n" *
            "Input path format:\n" *
            "  temp/samples/<chunk>/<sample>/edgelist.parquet\n" *
            "  (typically temp/samples/<chunk>/tree/edgelist.parquet)\n" *
            "\n" *
            "Output:\n" *
            "  output/gmrfmle-vs/<chunk>/<sample>/estimates.txt\n" *
            "  output/gmrfmle-vs_maxdeg<N>/<chunk>/<sample>/estimates.txt  (with --maxdeg)\n" *
            "\n" *
            "Examples:\n" *
            "  julia src/estimate/gmrfvs.jl temp/samples/full/tree/edgelist.parquet\n" *
            "  julia src/estimate/gmrfvs.jl temp/samples/full/tree/edgelist.parquet lnR --decompose=200\n" *
            "  julia src/estimate/gmrfvs.jl temp/samples/full/tree/edgelist.parquet lnR --maxdeg=20\n"
        )
        return 1
    end

    in_path = positional[1]
    outcome = (length(positional) >= 2) ? Symbol(positional[2]) : :lnR

    decomp_probes = 200
    maxdeg        = nothing
    for flag in flags
        if flag == "--decompose"
            decomp_probes = 200
        elseif startswith(flag, "--decompose=")
            decomp_probes = parse(Int, split(flag, '=', limit=2)[2])
        elseif flag == "--no-decompose"
            decomp_probes = 0
        elseif startswith(flag, "--maxdeg=")
            maxdeg = parse(Int, split(flag, '=', limit=2)[2])
            maxdeg >= 1 || error("--maxdeg must be >= 1, got $maxdeg")
        end
    end

    isfile(in_path) || error("Input file not found: $in_path")

    chunk, sample_id, out_path = parse_sample_path(in_path)

    # Redirect to a parallel directory when --maxdeg is active so baseline
    # results in output/gmrfvs/ are never overwritten.
    if maxdeg !== nothing
        out_path = replace(out_path, "output/gmrfmle-vs/" => "output/gmrfmle-vs_maxdeg$(maxdeg)/", count=1)
    end

    out_dir = dirname(out_path)
    mkpath(out_dir)

    @printf("Reading: %s\n", in_path)
    df = Parquet2.readfile(in_path) |> DataFrame
    @printf("Loaded rows: %d\n", nrow(df))

    if maxdeg !== nothing
        df = filter_maxdeg(df, maxdeg; verbose=true)
        nrow(df) > 0 || error("No edges remain after maxdeg=$maxdeg filter.")
    end

    r = estimate_vs(
        df;
        outcome=outcome,
        HUTCH_M=30,
        HUTCH_K=30,
        CG_TOL=1e-6,
        CG_MAXITER=700,
        iters=1000,
        seed=20260126,
        verbose=true,
        decomp_probes=decomp_probes
    )

    open(out_path, "w") do io
        @printf(io, "GMRF VS MLE (Variance-Stable Q, Hutch/SLQ + PCG)\n")
        @printf(io, "Chunk=%s | Sample=%s\n", chunk, sample_id)
        @printf(io, "Input=%s\n", in_path)
        @printf(io, "Outcome=%s\n", String(outcome))
        if maxdeg !== nothing
            @printf(io, "MaxDeg=%d\n", maxdeg)
        end
        @printf(io, "Seed=%d\n", r.seed)
        @printf(io, "N_F=%d, N_M=%d, K=%d, n=%d\n", r.N_F, r.N_M, r.K, r.n)
        @printf(io, "y_std=%.6g (scaling factor)\n", r.y_std)
        @printf(io, "Converged: %s | Iterations: %d | Obj evals: %d | Time: %.1fs\n",
                string(r.converged), r.iterations, r.obj_evals, r.opt_time)
        @printf(io, "NLL (scaled): %.6f\n", r.nll)
        @printf(io, "Estimates (structural units):\n")
        @printf(io, "  rho        = %.6f\n", r.rho)
        @printf(io, "  sigma_a    = %.6f\n", r.sigma_a)
        @printf(io, "  sigma_z    = %.6f\n", r.sigma_z)
        @printf(io, "  sigma_eps  = %.6f\n", r.sigma_eps)
        if r.decomp !== nothing
            d = r.decomp
            @printf(io, "\nVariance Decomposition (Hutchinson, m=%d, PCG converged %d/%d):\n",
                    d.probes, d.pcg_converged, d.probes)
            @printf(io, "  V_firm     = %+.6f  (firm effects; parametrised by sigma_a)\n",  d.V_firm)
            @printf(io, "  V_manager  = %+.6f  (manager effects; parametrised by sigma_z)\n", d.V_manager)
            @printf(io, "  V_cross    = %+.6f  (signed covariance; negative when rho < 0)\n", d.V_cross)
            @printf(io, "  V_eps      = %+.6f\n", d.V_eps)
            @printf(io, "  V_total    = %+.6f\n", d.V_total)
            if d.V_total > 0
                @printf(io, "Variance shares:\n")
                @printf(io, "  Share_firm     = %+.4f\n", d.V_firm    / d.V_total)
                @printf(io, "  Share_manager  = %+.4f\n", d.V_manager / d.V_total)
                @printf(io, "  Share_cross    = %+.4f\n", d.V_cross   / d.V_total)
                @printf(io, "  Share_eps      = %+.4f\n", d.V_eps     / d.V_total)
            end
        end
    end

    @printf("Wrote: %s\n", out_path)
    return 0
end

if abspath(PROGRAM_FILE) == @__FILE__
    exit(main())
end
